const stock1 = [
    { id: 1, img: "../assets/anne1.webp", nombre: "Anne With An E", desc: "La dulce y adorada Anne, no podía dejar de tejer este personaje. La amamos ❤️. El diseño crochetil es de mi autoria. Mi representación de Anne tiene 23cm de largo, tejida en hilo de algodón.", precio: 1500 },
    { id: 2, img: "../assets/dino.webp", nombre: "Dinosaurio", desc: "Sencillos, combinables y amorosos 🤍🦕Tejidos en hilo de algodón🦕16cm de alto🦕En stock colores: rojo+rosado / marrón+beige / beige+verde / amarillo", precio: 900 },
    { id: 3, img: "../assets/koala.webp", nombre: "Koala", desc: "Él es Lean el Koala. ▶Tiene 15cm de alto y mucho mucho relleno blandito para ser abrazado y amado por tu bebé ❤▶ Materiales utilizados: lana y vellón, bien aptos para menores de 3 añitos (al no tener ningún elemento pequeño y de plástico). ▶El bordado del nombre de tu bebé va incluido en el precio (este justamente va para quien le dio su nombre). ▶Combinación de colores de la ropita a elección y gusto del cliente 🎉", precio: 1400 },
    { id: 4, img: "../assets/pika.webp", nombre: "Pikachu", desc: "Díganme si no es un bombón este pikachu tejido 😍 Diseño propio.", precio: 1200 },
]
const stock2 = [
    { id: 5, img: "../assets/osito.webp", nombre: "Osito con bufanda", desc: "El osito 30cm de largo / tejido en hilo de algodón / apto -3 añitos. Las #hojas son señaladores de libros, bien otoñales(pero éstas no crujen cuando las pisas🍁)", precio: 1450 },
    { id: 6, img: "../assets/bb.webp", nombre: "BB-8", desc: "BB-8 es un droide de la saga de Star Wars. La mayor parte de su cuerpo estaba formado por una esfera metálica que le permitía rodar para desplazarse,en su mayoría era de color blanco con algunos tonos naranja, tenía una cabeza en forma de domo [...] Como verán, está mezclado con técnica tapestry... Conocen?.", precio: 900 },
    { id: 7, img: "../assets/cutu.webp", nombre: "Cthulhu", desc: "Cthulhu es una entidad cósmica representada por el escritor estadounidense de terror Howard Phillips Lovecraft y representada por primera vez en el cuento La llamada de Cthulhu (The Call of Cthulhu), publicado en la revista estadounidense Weird Tales en 1928. Considerado un Primigenio dentro de las entidades cósmicas, la criatura ha aparecido desde entonces en numerosas referencias de la cultura popular. Cthulhu es descrito como la convergencia de un pulpo, un dragón y una caricatura de forma humana.", precio: 980 },
    { id: 8, img: "../assets/conejito.webp", nombre: "Conejito con moño", desc: "Amigurumi Conejo. Tejido con hilo de algodón. 33cm de largo.", precio: 1100 },
]